# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/denis/CLionProjects/os_unix_myinit

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/denis/CLionProjects/os_unix_myinit

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/denis/CLionProjects/os_unix_myinit/CMakeFiles /home/denis/CLionProjects/os_unix_myinit//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/denis/CLionProjects/os_unix_myinit/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named os_unix_myinit

# Build rule for target.
os_unix_myinit: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 os_unix_myinit
.PHONY : os_unix_myinit

# fast build rule for target.
os_unix_myinit/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/os_unix_myinit.dir/build.make CMakeFiles/os_unix_myinit.dir/build
.PHONY : os_unix_myinit/fast

src/config_reading.o: src/config_reading.c.o
.PHONY : src/config_reading.o

# target to build an object file
src/config_reading.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/os_unix_myinit.dir/build.make CMakeFiles/os_unix_myinit.dir/src/config_reading.c.o
.PHONY : src/config_reading.c.o

src/config_reading.i: src/config_reading.c.i
.PHONY : src/config_reading.i

# target to preprocess a source file
src/config_reading.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/os_unix_myinit.dir/build.make CMakeFiles/os_unix_myinit.dir/src/config_reading.c.i
.PHONY : src/config_reading.c.i

src/config_reading.s: src/config_reading.c.s
.PHONY : src/config_reading.s

# target to generate assembly for a file
src/config_reading.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/os_unix_myinit.dir/build.make CMakeFiles/os_unix_myinit.dir/src/config_reading.c.s
.PHONY : src/config_reading.c.s

src/daemonization.o: src/daemonization.c.o
.PHONY : src/daemonization.o

# target to build an object file
src/daemonization.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/os_unix_myinit.dir/build.make CMakeFiles/os_unix_myinit.dir/src/daemonization.c.o
.PHONY : src/daemonization.c.o

src/daemonization.i: src/daemonization.c.i
.PHONY : src/daemonization.i

# target to preprocess a source file
src/daemonization.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/os_unix_myinit.dir/build.make CMakeFiles/os_unix_myinit.dir/src/daemonization.c.i
.PHONY : src/daemonization.c.i

src/daemonization.s: src/daemonization.c.s
.PHONY : src/daemonization.s

# target to generate assembly for a file
src/daemonization.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/os_unix_myinit.dir/build.make CMakeFiles/os_unix_myinit.dir/src/daemonization.c.s
.PHONY : src/daemonization.c.s

src/logger.o: src/logger.c.o
.PHONY : src/logger.o

# target to build an object file
src/logger.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/os_unix_myinit.dir/build.make CMakeFiles/os_unix_myinit.dir/src/logger.c.o
.PHONY : src/logger.c.o

src/logger.i: src/logger.c.i
.PHONY : src/logger.i

# target to preprocess a source file
src/logger.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/os_unix_myinit.dir/build.make CMakeFiles/os_unix_myinit.dir/src/logger.c.i
.PHONY : src/logger.c.i

src/logger.s: src/logger.c.s
.PHONY : src/logger.s

# target to generate assembly for a file
src/logger.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/os_unix_myinit.dir/build.make CMakeFiles/os_unix_myinit.dir/src/logger.c.s
.PHONY : src/logger.c.s

src/main.o: src/main.c.o
.PHONY : src/main.o

# target to build an object file
src/main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/os_unix_myinit.dir/build.make CMakeFiles/os_unix_myinit.dir/src/main.c.o
.PHONY : src/main.c.o

src/main.i: src/main.c.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/os_unix_myinit.dir/build.make CMakeFiles/os_unix_myinit.dir/src/main.c.i
.PHONY : src/main.c.i

src/main.s: src/main.c.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/os_unix_myinit.dir/build.make CMakeFiles/os_unix_myinit.dir/src/main.c.s
.PHONY : src/main.c.s

src/sub_processes.o: src/sub_processes.c.o
.PHONY : src/sub_processes.o

# target to build an object file
src/sub_processes.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/os_unix_myinit.dir/build.make CMakeFiles/os_unix_myinit.dir/src/sub_processes.c.o
.PHONY : src/sub_processes.c.o

src/sub_processes.i: src/sub_processes.c.i
.PHONY : src/sub_processes.i

# target to preprocess a source file
src/sub_processes.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/os_unix_myinit.dir/build.make CMakeFiles/os_unix_myinit.dir/src/sub_processes.c.i
.PHONY : src/sub_processes.c.i

src/sub_processes.s: src/sub_processes.c.s
.PHONY : src/sub_processes.s

# target to generate assembly for a file
src/sub_processes.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/os_unix_myinit.dir/build.make CMakeFiles/os_unix_myinit.dir/src/sub_processes.c.s
.PHONY : src/sub_processes.c.s

src/utils.o: src/utils.c.o
.PHONY : src/utils.o

# target to build an object file
src/utils.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/os_unix_myinit.dir/build.make CMakeFiles/os_unix_myinit.dir/src/utils.c.o
.PHONY : src/utils.c.o

src/utils.i: src/utils.c.i
.PHONY : src/utils.i

# target to preprocess a source file
src/utils.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/os_unix_myinit.dir/build.make CMakeFiles/os_unix_myinit.dir/src/utils.c.i
.PHONY : src/utils.c.i

src/utils.s: src/utils.c.s
.PHONY : src/utils.s

# target to generate assembly for a file
src/utils.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/os_unix_myinit.dir/build.make CMakeFiles/os_unix_myinit.dir/src/utils.c.s
.PHONY : src/utils.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... os_unix_myinit"
	@echo "... src/config_reading.o"
	@echo "... src/config_reading.i"
	@echo "... src/config_reading.s"
	@echo "... src/daemonization.o"
	@echo "... src/daemonization.i"
	@echo "... src/daemonization.s"
	@echo "... src/logger.o"
	@echo "... src/logger.i"
	@echo "... src/logger.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/sub_processes.o"
	@echo "... src/sub_processes.i"
	@echo "... src/sub_processes.s"
	@echo "... src/utils.o"
	@echo "... src/utils.i"
	@echo "... src/utils.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

